### PR TITLE
Biom format compatability

### PR DESCRIPTION
**Pull request by mortonjt**
This addresses #660 and adds compatibility to the biom-format.

The following have been addressed
- [x] Tutorial is added show inghow LDVAE can be used to analyze microbiome data.
- [x] biom is an optional dependency
- [x] a read_biom function is added to locally load biom tables

There are some slight hiccups regarding how to keep track of the sample names (see 2nd to last code block in the notebook). This will likely be a recurring issue for users and may need to be addressed in a future pull request.

### CODE REVIEW

**Comment by galenxing** [comment]
Hey @mortonjt, 

Thanks for the PR! We're currently doing a major refactor of our Datasets so once it's finished, we can review and port this Biom compatibility over.

**Comment by adamgayoso** [comment]
@mortonjt we are refactoring the dataset module to only use anndata. We can add a convenience method to read biom data and make it into anndata format. I'm just wondering, is this the most popular file type for microbiome data? Should the `scvi.dataset.read_biom(filename, backup_url=...)` function have any other functionality? Thanks!

**Comment by mortonjt** [comment]
Yes, I'd say that biom is the most common file format for sparse microbiome count tables. It looks like the data structures behind anndata are very similar to biom - I'm almost wondering if a `to_anndata` method would be appropriate to add directly into the biom-format repository.

One thing that I noticed with previous versions of scvi is that scvi loses information about the sample name (in your case the cell id).  It would make it more seamless to retain both row / column identifiers, addition to row / column metadata.

**Comment by adamgayoso** [comment]
> I'm almost wondering if a to_anndata method would be appropriate to add directly into the biom-format repository.

This seems like a better solution to me as it opens up the possibility of using many more single-cell algorithms with microbiome data. Anndata has the capability to preserve all row and column identifiers and associated metadata.

**Comment by adamgayoso** [comment]
Hi @mortonjt, the time has now come. It would be extremely helpful if you refactored your tutorial to

1. Work in google colab (don't worry about it being tested with pytest)
2. Use the new 1.0 API
3. Submitted a PR to the contributed folder in [this repo](https://github.com/YosefLab/scvi_tutorials)

To see how the new API works please look at the quick start tutorial [here](https://scvi--750.org.readthedocs.build/en/750/user_guide/index.html).

Full API documentation is also available on that page. Note that for LDVAE it's now `scvi.models.LinearSCVI`.

**Comment by mortonjt** [comment]
Great!!  I'll make sure to take another look at this (it'll probably happen
in ~3 weeks due to ongoing manuscript submissions).

**Comment by adamgayoso** [comment]
Thanks! I'm going to close this PR for now.

**Comment by mortonjt** [comment]
Hi @adamgayoso , I'm taking another look at this; in order for the tutorial to work, we'd still need to have a BiomDataset object right? The PR you made to Biom enables the conversion to anndata, but that object will still need to be read in through the biom api, right?

**Comment by adamgayoso** [comment]
@mortonjt, the tutorial will not be tested, so it should work entirely in google colab. You can use the first cell in our user guide notebooks as an example. 

> we'd still need to have a BiomDataset object right? The PR you made to Biom enables the conversion to anndata, but that object will still need to be read in through the biom api, right?

Correct, the first lines of the tutorial would download the biom file and load it with the biom api and then convert to anndata, or whatever is the most conventional workflow for this type of data at first.

**Pull request closed without merging**
