### PR TITLE
Update Documentation to explain how we make releases and backport patches

### PR DESCRIPTION
**Pull request by watiss**

### CODE REVIEW

**Review by adamgayoso — CHANGES_REQUESTED** [review]
LGTM except I'm not a fan of the extra link in the nav bar. I think all in one for now is fine as within a page you get the right side nav. In the future we can have multiple pages inside "contributing". Thoughts?

**Comment by watiss** [comment]
Personally, I kind of like the separation. This is what Pandas does too: https://pandas.pydata.org/docs/development/maintaining.html. But I'm fine with leaving it as it is today and updating later if we see fit.
Update coming in shortly

**Review by adamgayoso — APPROVED** [review]
LGTM. We can make it like Pandas soon (multiple pages within a development tab)

**Comment by adamgayoso** [comment]
@meeseeksdev backport to 0.14.x

**Pull request merged**
