### PR TITLE
furo docs theme

### LINKED ISSUE #1155: Add doc extension for link preview
https://github.com/wpilibsuite/sphinxext-opengraph

Would be nice when sharing links with people

### PR DESCRIPTION
**Pull request by adamgayoso**
New features

- Dark mode
- Better CSS formatting for tutorials
- Cleaner feel to docs
- Fixes #1155

View built docs on this branch [here](https://scvi--1290.org.readthedocs.build/en/1290/index.html#) (best to do in private window due to browser caching)

Everything generally looks good in both light and dark mode. We can force white backgrounds on images in the first cell of tutorials to make those look good in dark mode. We can also refactor the notebook gallery images in a future release.

### CODE REVIEW

**Comment by galenxing** [comment]
Looks cool! Would be nice if the api methods were all one liners in the left side bar (e.g. make the text smaller or make the sidebar larger).

**Comment by adamgayoso** [comment]
> Looks cool! Would be nice if the api methods were all one liners in the left side bar (e.g. make the text smaller or make the sidebar larger).

This should be fixed now

**Comment by watiss** [comment]
I think I like our current one a little better, but this is also nice.

Couple of notes:
- Some tutorial features seem broken in dark mode, such as this umap:
Screen Shot 2022-02-13 at 11 02 36 PM

- Should we have a side menu drop-down for User guides like we do for Tutorials?

**Comment by adamgayoso** [comment]
> Should we have a side menu drop-down for User guides like we do for Tutorials?

I removed this because it's going to be too long eventually -- scikit-learn and pytorch do not make use of long content sidebars

@watiss The images will be rerun when we rerun all the tutorials and white background on images will be forced.

**Review by watiss — APPROVED** [review]

**Comment by jjhong922** [comment]
Dark mode boxes could be slightly lighter here
image

Also these boxes can just match the ones on the homepage if possible (or change from images to badges to make it even simpler
image

Otherwise I'm a big fan of this new theme!

**Pull request merged**
