### PR TITLE
Sphinx panels for docs index page

### PR DESCRIPTION
**Pull request by adamgayoso**

### CODE REVIEW

**Comment by adamgayoso** [comment]
There's weird offset of the images inside the cards. Also we can do this to the installation page if we wish:

https://pandas.pydata.org/pandas-docs/stable/getting_started/index.html

(top part)

**Comment by jjhong922** [comment]
What's the reason for this change? The way it looked before looked nicer imo

**Comment by jjhong922** [comment]
Answered offline: makes code way cleaner to do the same thing and make more things clickable. Styles will be fixed

**Review by jjhong922 — APPROVED** [review]
clean

**Pull request merged**
