### PR TITLE
[WIP]: refactor fclayers for scarches

### PR DESCRIPTION
**Pull request by adamgayoso**

### CODE REVIEW

**Comment by adamgayoso** [comment]
@M0hammadL, @Koncopd, @Cottoneyejoe95, this is what I was envisioning earlier. Now we can just load the state dict with `strict=False` and add a few more nodes to the parameter list. The implementation is a bit slower than our current code though and I'm trying to figure out why.

**Comment by adamgayoso** [comment]
@M0hammadL, @Koncopd, @Cottoneyejoe95 please see #813 instead. I think using the hooks could be better as it doesn't disrupt a normal model training. It could be a little slower for the query dataset update as gradients will be computed on every linear layer that receives the categoricals

**Comment by M0hammadL** [comment]
Hi Adam, thx a lot for pushing.   @Koncopd, @Cottoneyejoe95 would you please check?

 I will also look in detail at the weekend.

**Comment by M0hammadL** [comment]
@adamgayoso  is this cover totalVI and gimVI too?

**Comment by Koncopd** [comment]
@M0hammadL yes, i'll check.

**Comment by adamgayoso** [comment]
@M0hammadL, @Cottoneyejoe95  thanks for sharing the data. The PR will cover totalVI eventually. gimVI is a bit more difficult and not sure we should implement it here.

**Pull request closed without merging**
